services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Novactive\EzRssFeedBundle\Controller\RssFeedViewController: ~

  Novactive\EzRssFeedBundle\Form\RssFeedItemsType:
    tags:
    - { name: form.type }

  Novactive\EzRssFeedBundle\Form\Type\TreeDiscoveryType:
    tags:
    - { name: form.type, alias: field.tree_discovery }

  Novactive\EzRssFeedBundle\Services\RssFeedsService:
