system:
  default:
    content_view:
      rss_line:
        default:
          template: "EzRssFeedBundle:default:content/rss_line.html.twig"
          match: []

      asset_image:
        default:
          template: "EzRssFeedBundle:default:content/fields/asset_image.html.twig"
          match: []
