system:
    default:
        content_view:
            rss_line:
                default:
                    template: "@EzRssFeed/default/content/rss_line.html.twig"
                    match: ~

            rss_image:
                default:
                    template: "@EzRssFeed/default/content/rss_image.html.twig"
                    match: ~
